name: IaC Pipeline

on:
  push:
    branches:
      - develop
      - main
      - 'feature/*'
      - 'hotfix/*'

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 14
      DEV_ENV: dev
      TEST_ENV: test
      FEATURE_ENV: feature

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - name: Set Environment
        id: set-env
        run: |
          if [[ "${{ github.ref }}" == refs/heads/develop ]]; then
            echo "ENVIRONMENT=${{ env.DEV_ENV }}" >> $GITHUB_ENV
            echo "TF_VARS_FILE=dev.tfvars" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == refs/heads/main ]]; then
            echo "ENVIRONMENT=${{ env.TEST_ENV }}" >> $GITHUB_ENV
            echo "TF_VARS_FILE=uat.tfvars" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == refs/heads/feature/* ]] || [[ "${{ github.ref }}" == refs/heads/hotfix/* ]]; then
            echo "ENVIRONMENT=${{ env.FEATURE_ENV }}" >> $GITHUB_ENV
            echo "TF_VARS_FILE=feature.tfvars" >> $GITHUB_ENV
          fi

          
      - name: Call Terraform Workflow
        uses: ./.github/workflows/terraform-reusable.yml
        with:
          path: S3Bucket   # Adjust to your Terraform configuration path


