name: Reusable Workflow

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        type: string
      tf_vars_file:
        description: 'Terraform variables file'
        required: false
        type: string
      path:
        description: 'Path to Terraform configuration'
        required: true
        type: string
    
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      aws_region:
        required: true


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to ${{ inputs.environment }}
        run: |
          echo "Deploying to ${{ inputs.environment }} environment"
      - name: Terraform Validate
        run: terraform validate
  
      - name: Terraform Plan
        run: terraform plan -var-file=${{ inputs.tf_vars_file }} -out=tfplan
  
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
          # Consider adding an `if` condition here to control when to apply
